// Generated by gencpp from file ov_core/WheelPulses.msg
// DO NOT EDIT!


#ifndef OV_CORE_MESSAGE_WHEELPULSES_H
#define OV_CORE_MESSAGE_WHEELPULSES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ov_core
{
template <class ContainerAllocator>
struct WheelPulses_
{
  typedef WheelPulses_<ContainerAllocator> Type;

  WheelPulses_()
    : header()
    , wheel_front_left(0)
    , wheel_front_right(0)
    , wheel_rear_left(0)
    , wheel_rear_right(0)  {
    }
  WheelPulses_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , wheel_front_left(0)
    , wheel_front_right(0)
    , wheel_rear_left(0)
    , wheel_rear_right(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _wheel_front_left_type;
  _wheel_front_left_type wheel_front_left;

   typedef int32_t _wheel_front_right_type;
  _wheel_front_right_type wheel_front_right;

   typedef int32_t _wheel_rear_left_type;
  _wheel_rear_left_type wheel_rear_left;

   typedef int32_t _wheel_rear_right_type;
  _wheel_rear_right_type wheel_rear_right;





  typedef boost::shared_ptr< ::ov_core::WheelPulses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ov_core::WheelPulses_<ContainerAllocator> const> ConstPtr;

}; // struct WheelPulses_

typedef ::ov_core::WheelPulses_<std::allocator<void> > WheelPulses;

typedef boost::shared_ptr< ::ov_core::WheelPulses > WheelPulsesPtr;
typedef boost::shared_ptr< ::ov_core::WheelPulses const> WheelPulsesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ov_core::WheelPulses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ov_core::WheelPulses_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ov_core::WheelPulses_<ContainerAllocator1> & lhs, const ::ov_core::WheelPulses_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.wheel_front_left == rhs.wheel_front_left &&
    lhs.wheel_front_right == rhs.wheel_front_right &&
    lhs.wheel_rear_left == rhs.wheel_rear_left &&
    lhs.wheel_rear_right == rhs.wheel_rear_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ov_core::WheelPulses_<ContainerAllocator1> & lhs, const ::ov_core::WheelPulses_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ov_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ov_core::WheelPulses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ov_core::WheelPulses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ov_core::WheelPulses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ov_core::WheelPulses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ov_core::WheelPulses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ov_core::WheelPulses_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ov_core::WheelPulses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78f13032efdb736ac95f293d65a603bf";
  }

  static const char* value(const ::ov_core::WheelPulses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78f13032efdb736aULL;
  static const uint64_t static_value2 = 0xc95f293d65a603bfULL;
};

template<class ContainerAllocator>
struct DataType< ::ov_core::WheelPulses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ov_core/WheelPulses";
  }

  static const char* value(const ::ov_core::WheelPulses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ov_core::WheelPulses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int32 wheel_front_left\n"
"int32 wheel_front_right\n"
"int32 wheel_rear_left\n"
"int32 wheel_rear_right\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ov_core::WheelPulses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ov_core::WheelPulses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.wheel_front_left);
      stream.next(m.wheel_front_right);
      stream.next(m.wheel_rear_left);
      stream.next(m.wheel_rear_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelPulses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ov_core::WheelPulses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ov_core::WheelPulses_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "wheel_front_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheel_front_left);
    s << indent << "wheel_front_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheel_front_right);
    s << indent << "wheel_rear_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheel_rear_left);
    s << indent << "wheel_rear_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheel_rear_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OV_CORE_MESSAGE_WHEELPULSES_H
